apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  selector:
    app: calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
      nodePort: 30007
  type: NodePort  # Use NodePort or ClusterIP based on your setup
